before_script:
  - apk add --update ca-certificates openssl && update-ca-certificates
  - wget https://agentx20.sr.bham.ac.uk:8080/static/scripts/brumsofttest.sh
  - chmod +x brumsofttest.sh

Physics2.7:
  script:
    - ./brumsofttest.sh -s https://agentx20.sr.bham.ac.uk:8080 -u 1 -t 12 -g $CI_COMMIT_SHA
    - ./brumsofttest.sh -s https://agentx20.sr.bham.ac.uk:8080 -u 1 -t 13 -g $CI_COMMIT_SHA
    - ./brumsofttest.sh -s https://agentx20.sr.bham.ac.uk:8080 -u 1 -t 14 -g $CI_COMMIT_SHA

Physics3.5:
  script:
    - ./brumsofttest.sh -s https://agentx20.sr.bham.ac.uk:8080 -u 1 -t 15 -g $CI_COMMIT_SHA
    - ./brumsofttest.sh -s https://agentx20.sr.bham.ac.uk:8080 -u 1 -t 16 -g $CI_COMMIT_SHA
    - ./brumsofttest.sh -s https://agentx20.sr.bham.ac.uk:8080 -u 1 -t 17 -g $CI_COMMIT_SHA 
