Physics2.7:
  script:
    - ./brumsofttest.sh -s http://agentx20.sr.bham.ac.uk:9555/ -u 1 -t 8 -g $CI_COMMIT_SHA

Physics3.5:
  script:
    - ./brumsofttest.sh -s http://agentx20.sr.bham.ac.uk:9555/ -u 1 -t 7 -g $CI_COMMIT_SHA
