before_script:
    - export CWD=$(pwd)
    - export PYTHONPATH=$PYTHONPATH:$CWD
    # - cd /finesse
    # - rm kat
    # - git reset --hard
    # - git checkout develop
    # - git pull
    # - echo "Building Finesse..."
    # - ./finesse.sh --build > /dev/null 2>&1
    # - echo "Sucessfuly built Finesse"
    - cd $CWD
    
python_3:
    script:
        - source /setup.sh
        - kat -v
        - which python3
        - python3 --version
        - cd test
        - python3 run_tests.py
        
python_2:
    script:
        - source /setup.sh
        - kat -v
        - which python2.7
        - python2.7 --version
        - cd test
        - python2.7 run_tests.py