before_script:
    - export CWD=$(pwd)
    - source /etc/environment # Why this doesn't happen automatically I don't know...
    # - cd /finesse
    # - rm kat
    # - git reset --hard
    # - git checkout develop
    # - git pull
    # - echo "Building Finesse..."
    # - ./finesse.sh --build > /dev/null 2>&1
    # - echo "Sucessfuly built Finesse"
    - cd $CWD
    
python_3:
    script:
        - kat -v
        - which python3
        - python3 --version
        - python3 test/run_tests.py
        
python_2:
    script:
        - kat -v
        - which python2.7
        - python2.7 --version
        - python2.7 test/run_tests.py