Physics2.7:
  script:
    - python brumsofttest.py http://agentx20.sr.bham.ac.uk:9555/ 1 8 $CI_COMMIT_SHA
  tags:
    - best

Physics3.5:
  script:
    - python brumsofttest.py http://agentx20.sr.bham.ac.uk:9555/ 1 7 $CI_COMMIT_SHA
  tags:
    - best
